#! /bin/bash
usage()
{
cat << EOF
usage: $0 options

This script measures the time taken by qhull for random points.

OPTIONS:
   -h      Show this message
   -e      Exponent of the number of points. 10^e
   -d      Dimensions of a point.
   -t      Time outin seconds. Default 5 seconds.
EOF
}

EXPONENT=
DIMENSIONS=
TIME_OUT=5
while getopts “he:d:t:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         e)
             EXPONENT=$OPTARG
             ;;
         d)
             DIMENSIONS=$OPTARG
             ;;
         t)
             TIME_OUT=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

if [[ -z $EXPONENT ]] || [[ -z $DIMENSIONS ]]
then
     usage
     exit 1
fi

RESULT=`./timedqhull "-d" "${DIMENSIONS}" "-e" "${EXPONENT}" "-t" "${TIME_OUT}"`
RESULT="${RESULT#*\: }"
RESULT="N${EXPONENT} D${DIMENSIONS} T${RESULT}"
echo $RESULT